-- ============================================================
-- FIX: change identity columns from ALWAYS to BY DEFAULT
-- Lets upsert/insert send an explicit id for existing rows.
-- Idempotent - safe to run multiple times.
-- ============================================================

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'jobs','applications','saved_resumes','companies','testimonials','videos'
  ] LOOP
    BEGIN
      EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id SET GENERATED BY DEFAULT', t);
    EXCEPTION WHEN undefined_table THEN NULL;
             WHEN undefined_column THEN NULL;
    END;
  END LOOP;
END $$;

NOTIFY pgrst, 'reload schema';
